### ISSUE TITLE
Blocklist

### ISSUE THREAD

**Issue by santiago-se** [2008Choco/VeinMiner#129]
Sand can still be VeinMined if it is by deafault in the Blocklist even if i put sand to all blocklist

**Comment by 2008Choco** [comment]
I'm not sure I understand. The `All` block list will add those blocks to all other categories' block lists. If you want sand to _not_ be in the block list, you would remove it. If your list is empty, you have to use `[]` to denote that the list is empty, otherwise VeinMiner will try to use the default. For example:
```yaml
Shovel:
  Items:
  - 'minecraft:wooden_shovel'
  - 'minecraft:stone_shovel'
  - 'minecraft:golden_shovel'
  - 'minecraft:iron_shovel'
  - 'minecraft:diamond_shovel'
  - 'minecraft:netherite_shovel'
  BlockList: [] # This is an empty block list
```
Although I'm not sure why you would want an empty block list in any category other than `All` or `Hand`.
