### ISSUE TITLE
Add option to specify multiple Types in ToolTemplate

### ISSUE THREAD

**Issue by RalphORama** [2008Choco/VeinMiner#34]
Apologies if this option is already available and I missed it in the documentation.

I'd like the ability to specify multiple tool types in the `ToolTemplate` configuration directive, i.e. iron, gold, diamond.

The current config looks like:

```yaml
ToolTemplates:
  Precedence: CATEGORY_SPECIFIC_GLOBAL_DEFAULT
  Global:
    Type: 'iron'     # <-- This type can be ANY type at all
  Pickaxe:
    # This type MUST be one of the tools defined by the Pickaxe category 
    # (i.e. wood, stone, gold, iron, etc. pickaxes)
    Type: 'diamond_pickaxe'
```

I'd like the option to do something like this:

```yaml
ToolTemplates:
  Precedence: CATEGORY_SPECIFIC_GLOBAL_DEFAULT
  Global:
    Type: 
      - 'iron'
      - 'gold'
      - 'diamond' 
  Pickaxe:
    # This type MUST be one of the tools defined by the Pickaxe category 
    # (i.e. wood, stone, gold, iron, etc. pickaxes)
    Type: 
      - 'iron_pickaxe'
      - 'diamond_pickaxe'
```
