### ISSUE TITLE
Veinminer does not work on netherite tools

### ISSUE THREAD

**Issue by Higgins4k** [2008Choco/VeinMiner#39]

**Comment by 2008Choco** [comment]
I can confirm that it does. Be sure you've added the new tools to your tool lists (categories.yml or from in game with `/veinminer toollist <category> add <tool>`) and the new blocks to your block lists.

**Comment by Fundryi** [comment]
Weird, for me, it doesn't work and If I wanna use the command you listed above to add them it says "Invalid tool category: *Axe/axe*"

```
Axe:
  MaxVeinSize: 128
  Items:
  - 'minecraft:wooden_axe'
  - 'minecraft:stone_axe'
  - 'minecraft:golden_axe'
  - 'minecraft:iron_axe'
  - 'minecraft:diamond_axe
  - 'minecraft:netherite_axe'

Hoe:
  MaxVeinSize: 128
  Items:
  - 'minecraft:wooden_hoe'
  - 'minecraft:stone_hoe'
  - 'minecraft:golden_hoe'
  - 'minecraft:iron_hoe'
  - 'minecraft:diamond_hoe'
  - 'minecraft:netherite_hoe'

Pickaxe:
  MaxVeinSize: 128
  Items:
  - 'minecraft:wooden_pickaxe'
  - 'minecraft:stone_pickaxe'
  - 'minecraft:golden_pickaxe'
  - 'minecraft:iron_pickaxe'
  - 'minecraft:diamond_pickaxe'
  - 'minecraft:netherite_pickaxe'

Shears:
  MaxVeinSize: 128
  Items:
  - 'minecraft:shears'

Shovel:
  MaxVeinSize: 128
  Items:
  - 'minecraft:wooden_shovel'
  - 'minecraft:stone_shovel'
  - 'minecraft:golden_shovel'
  - 'minecraft:iron_shovel'
  - 'minecraft:diamond_shovel'
  - 'minecraft:netherite_shovel'

# ExampleCategory:
#   MaxVeinSize: 10
#   Items:
#   - 'minecraft:torch'
#   - 'minecraft:redstone_torch':
#     Name: "&6My Cool Torch!"
#     Lore:
#     - "First line!"
#     - "&5Second line!"
#   - 'minecraft:potato':
#     Name: "&8Special item!"
#     MaxVeinSize: 128
#     IncludeEdges: false
```
